/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppChildOne {
        "parentClickHandler": Function;
    }
    interface AppChildTwo {
        "addText": (newText: any) => Promise<void>;
    }
    interface AppParent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAppChildOneElement extends Components.AppChildOne, HTMLStencilElement {
    }
    var HTMLAppChildOneElement: {
        prototype: HTMLAppChildOneElement;
        new (): HTMLAppChildOneElement;
    };
    interface HTMLAppChildTwoElement extends Components.AppChildTwo, HTMLStencilElement {
    }
    var HTMLAppChildTwoElement: {
        prototype: HTMLAppChildTwoElement;
        new (): HTMLAppChildTwoElement;
    };
    interface HTMLAppParentElement extends Components.AppParent, HTMLStencilElement {
    }
    var HTMLAppParentElement: {
        prototype: HTMLAppParentElement;
        new (): HTMLAppParentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-child-one": HTMLAppChildOneElement;
        "app-child-two": HTMLAppChildTwoElement;
        "app-parent": HTMLAppParentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppChildOne {
        "parentClickHandler"?: Function;
    }
    interface AppChildTwo {
    }
    interface AppParent {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-child-one": AppChildOne;
        "app-child-two": AppChildTwo;
        "app-parent": AppParent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-child-one": LocalJSX.AppChildOne & JSXBase.HTMLAttributes<HTMLAppChildOneElement>;
            "app-child-two": LocalJSX.AppChildTwo & JSXBase.HTMLAttributes<HTMLAppChildTwoElement>;
            "app-parent": LocalJSX.AppParent & JSXBase.HTMLAttributes<HTMLAppParentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
